services:
  - type: web
    name: arduino-laravel
    env: php
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer
      composer install
      npm install
      npm run dev
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:gwPBD2L0xMlXrgIkk150wM4bQ05NW/olQ/8eaNh3CUw=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: viaduct.proxy.rlwy.net
      - key: DB_PORT
        value: 17621
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ZJtiVodTjAyFrZSAXghqtmulhNewXZRu
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: http://your-domain.com
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: amirmansouri.dev@gmail.com
      - key: MAIL_PASSWORD
        value: yxwuhmrwotmbqxlj
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Arduino
      - key: JWT_SECRET
        value: YImp5uuJHC0uDymLabUPo95sSqH03h0rFPw6vOvqwY8hqOZv9oYUaE2vNtRc9zeD
      - key: FIREBASE_API_KEY
        value: AIzaSyCDkHQ89Xl4ezqJKrbOKqjo8YcmCkFoIuw
      - key: FIREBASE_AUTH_DOMAIN
        value: arduino2-81ecc.firebaseapp.com
      - key: FIREBASE_DATABASE_URL
        value: https://arduino2-81ecc.firebaseio.com
      - key: FIREBASE_PROJECT_ID
        value: arduino2-81ecc
      - key: FIREBASE_STORAGE_BUCKET
        value: arduino2-81ecc.appspot.com
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 583650644779
      - key: FIREBASE_APP_ID
        value: 1:583650644779:web:7937a64e96ab821b686b6e
      - key: FIREBASE_MEASUREMENT_ID
        value: G-931SVQ9Q9M
      - key: FIREBASE_CREDENTIALS
        value: storage/app/firebase/firebase_credentials.json
